apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginxgreen
spec:
  containers:
  - image: iam7hills/dockerdemo:nginx-green
    name: nginxgreen
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
